name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

# Always force the use of Go modules
env:
  GO111MODULE: on

jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.15.x,1.16.x,1.17.x]
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.31

  build:
    runs-on: ubuntu-latest

    # strategy set
    strategy:
      matrix:
        go: ["1.15", "1.16", "1.17", "1.18"]

    steps:
      # Setup the environment.
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version:  ${{ matrix.go }}
      # Checkout latest code
      - name: Checkout repo
        uses: actions/checkout@v2

      # Execute vert check
      - name: vert check
        run: bash ./ci/vet.sh -install && bash ./ci/vet.sh

      # Run tests
      - name: run tests
        run: |
          cd ./test
          go test -timeout=50m